# Generated by Django 5.2.7 on 2025-10-02 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emhaver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='pendencia',
            name='forma_pagamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='emhaver.formapagamento'),
        ),
    ]
