# Generated by Django 5.2.7 on 2025-10-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planoexercicio',
            name='ordem',
            field=models.PositiveIntegerField(default='1'),
            preserve_default=False,
        ),
    ]
