# Generated by Django 5.2.7 on 2025-10-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_planoexercicio_ordem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fim',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='registro',
            name='inicio',
            field=models.DateTimeField(),
        ),
    ]
